#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include <math.h>

#define SEED 100

unsigned char * initialise_image( int maxval, int xsize, int ysize, char* image_name, int argc, char** argv){

  unsigned int procs, rank, mpi_provided_thread_level;
  FILE* image_file=NULL;
  image_file = fopen(image_name, "w");
  int color_depth = 1 + ( maxval > 255 );
  fprintf(image_file, "P5\n# generated by\n# fraspecial \n%d %d\n%d\n", xsize, ysize, maxval);
  fclose(image_file);
  unsigned int size=xsize*ysize;  

  //printf("Generale - xsize: %d\n",xsize);
  MPI_Init_thread( &argc, &argv, MPI_THREAD_FUNNELED,
  &mpi_provided_thread_level);

  if ( mpi_provided_thread_level < MPI_THREAD_FUNNELED ) {
    printf("a problem arise when asking for MPI_THREAD_FUNNELED level\n");
    MPI_Finalize();
    exit( 1 );
  }

  MPI_Comm_size(MPI_COMM_WORLD, &procs);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);

  unsigned int rest=size%procs;
  printf("hello from proc %d/%d\n", rank, procs);
  printf("rest for proc %d: %d\n", rank, rest);

  printf("xsize: %d\n",xsize);
  unsigned int buffer_size=size/procs+(rank<rest);
  int seed=SEED*rank+procs;
  srand(seed);
  printf("buffer_size for proc %d: %d\n", rank, buffer_size);

  unsigned char* local_buffer = malloc(buffer_size*sizeof(unsigned char) );

  for ( int i = 0; i < buffer_size; i++ ){
    local_buffer[i] = maxval*round((double)rand()/(double)RAND_MAX);
    printf("Processor %d iteration %d = %d\n",rank, i, local_buffer[i]);
  }


  MPI_File fh;
  MPI_File_open(MPI_COMM_WORLD, image_name, MPI_MODE_WRONLY, MPI_INFO_NULL, &fh);
  MPI_File_set_view(fh, 40+(rank*buffer_size) + rest*(rank + 1 > rest), MPI_CHAR, MPI_CHAR,
                    "native", MPI_INFO_NULL);

  //  MPI_Barrier(MPI_COMM_WORLD);

  MPI_File_write_all(fh, local_buffer, buffer_size, MPI_CHAR, MPI_STATUS_IGNORE);

  printf("Processor %d wrote %d bytes\n", rank, buffer_size);

  MPI_File_close(&fh);
  MPI_Finalize();

}

/*
unsigned char * generate_image(struct Cell * grid, const  int size){
  unsigned char* cImage;

  cImage = calloc(size, sizeof(unsigned char) );
  for ( int i = 0; i < size; i++ ){
    unsigned char value = *((grid+i)->value);
    cImage[i] = value;
  }
  return cImage;
}*/
