#define SEED 100

unsigned char * initialise_image( int maxval, int xsize, int ysize, char* filename, int argc, char** argv){

  unsigned int size, rank, mpi_provided_thread_level;
  unsigned int rest=xsize%size;
  unsigned int buffer_size=xsize*ysize/size+(rank<rest);
  FILE* image_file=NULL;
  image_file = fopen(image_name, "w");
  int color_depth = 1 + ( maxval > 255 );
  fprintf(image_file, "P5\n# generated by\n# fraspecial \n%d %d\n%d\n", xsize, ysize, maxval);
  fclose(image_file);


  MPI_Init_thread( &argc, &argv, MPI_THREAD_FUNNELED,
  &mpi_provided_thread_level);

  if ( mpi_provided_thread_level < MPI_THREAD_FUNNELED ) {
    printf("a problem arise when asking for MPI_THREAD_FUNNELED
    level\n");
    MPI_Finalize();
    exit( 1 );
  }

  MPI_Comm_size(MPI_COMM_WORLD, &size);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);

  int seed=SEED+rank;
  srand(seed);
  unsigned char* local_buffer = malloc(buffer_size, sizeof(unsigned char) );

  for ( int i = 0; i < buffer_size; i++ ){
    local_buffer[i] = maxval*round((double)rand()/(double)RAND_MAX);
    priintf("Processor %d iteration %d = %d",rank, i, local_buffer[i]);
  }


  MPI_File fh;
  MPI_File_open(MPI_COMM_WORLD, filename,
                MPI_MODE_WRONLY | MPI_MODE_CREATE, MPI_INFO_NULL,
                &fh);
  MPI_File_set_view(fh, (rank*buffer_size) + rest*(rank + 1 > rest), MPI_BYTE, MPI_BYTE,
                    "native", MPI_INFO_NULL);

  //  MPI_Barrier(MPI_COMM_WORLD);

  MPI_File_write_all(fh, local_buffer, buffer_size, MPI_T, MPI_STATUS_IGNORE);

  printf("Processor %d wrote %d bytes\n", rank, buffer_size);

  MPI_File_close(&fh);
  MPI_Finalize();
}

/*
unsigned char * generate_image(struct Cell * grid, const  int size){
  unsigned char* cImage;

  cImage = calloc(size, sizeof(unsigned char) );
  for ( int i = 0; i < size; i++ ){
    unsigned char value = *((grid+i)->value);
    cImage[i] = value;
  }
  return cImage;
}*/
