void write_pgm_image(unsigned char *image, const int maxval, const int xsize, const int ysize, const char *image_name)
/*
* image        : a pointer to the memory region that contains the image
* maxval       : either 255 or 65536
* xsize, ysize : x and y dimensions of the image
* image_name   : the name of the file to be written
*
*/
{
    FILE* image_file=NULL;
    image_file = fopen(image_name, "w");
    // Writing header
    // The header's format is as follows, all in ASCII.
    // "whitespace" is either a blank or a TAB or a CF or a LF
    // - The Magic Number (see below the magic numbers)
    // - the image's width
    // - the height
    // - a white space
    // - the image's height
    // - a whitespace
    // - the maximum color value, which must be between 0 and 65535
    //
    // if he maximum color value is in the range [0-255], then
    // a pixel will be expressed by a single byte; if the maximum is
    // larger than 255, then 2 bytes will be needed for each pixel
    //
    int color_depth = 1 + ( maxval > 255 );

    fprintf(image_file, "P5\n# generated by\n# fraspecial \n%d %d\n%d\n", xsize, ysize, maxval);

    // Writing file
    fwrite(image, color_depth, xsize*ysize, image_file);

    fclose(image_file);
}


void read_pgm_image(unsigned char **image, int *maxval, int *xsize, int *ysize, const char *image_name)
/*
* image        : a pointer to the pointer that will contain the image
* maxval       : a pointer to the int that will store the maximum intensity in the image
* xsize, ysize : pointers to the x and y sizes
* image_name   : the name of the file to be read
*
*/
{
  FILE* image_file;
  image_file = fopen(image_name, "r");

  *image = NULL;
  *xsize = *ysize = *maxval = 0;

  char    MagicN[2];
  char   *line = NULL;
  size_t  k, n = 0;

  // get the Magic Number
  k = fscanf(image_file, "%2s%*c", MagicN );

  // skip all the comments
  k = getline( &line, &n, image_file);
  while ( (k > 0) && (line[0]=='#') )
  k = getline( &line, &n, image_file);

  if (k > 0)
  {
    k = sscanf(line, "%d%*c%d%*c%d%*c", xsize, ysize, maxval);
    if ( k < 3 )
    fscanf(image_file, "%d%*c", maxval);
  }
  else
  {
    *maxval = -1;         // this is the signal that there was an I/O error
    // while reading the image header
    free( line );
    return;
  }
  free( line );

  int color_depth = 1 + ( *maxval > 255 );
  unsigned int size = *xsize * *ysize * color_depth;

  if ( (*image = (unsigned char*)malloc( size )) == NULL )
  {
    fclose(image_file);
    *maxval = -2;         // this is the signal that memory was insufficient
    *xsize  = 0;
    *ysize  = 0;
    return;
  }

  if ( fread( *image, 1, size, image_file) != size )
  {
    free( image );
    image   = NULL;
    *maxval = -3;         // this is the signal that there was an i/o error
    *xsize  = 0;
    *ysize  = 0;
  }

  fclose(image_file);
  return;
}


void swap_image( unsigned char *image, int xsize, int ysize, int maxval )
/*
* This routine swaps the endianism of the memory area pointed
* to by ptr, by blocks of 2 bytes
*
*/
{
  if ( maxval > 255 )
  {
    // pgm files has the short int written in
    // big endian;
    // here we swap the content of the image from
    // one to another
    //
    unsigned int size = xsize * ysize;
    for ( int i = 0; i < size; i++ )
    ((unsigned short int*)image)[i] = swap(((unsigned short int*)image)[i]);
  }
  return;
}
