#!/bin/bash
# Name of the job
#SBATCH --no-requeue
#SBATCH --job-name="init"
#SBATCH --partition=EPYC
#SBATCH -N 1
#SBATCH --ntasks-per-node 128
#SBATCH --exclusive
#SBATCH --time=10:00
#SBATCH --output="./evolve_image.out"

echo LOADING MODULES...
echo
module load openMPI/4.1.5/gnu/12.2.1

echo COMPILING EXECUTABLES...
make clean; make;
echo -------------------------------------------------------------

echo CREATING IMAGE...
mpirun ./main.x -i -k 25000 -f conway.pgm

echo IMAGE CREATED